name: ssh
shortDesc: Allows you to ssh directly from `kubectl`
longDesc: |
  Opens up an SSH connection to the node that you pass into the command,
  allowing you to work faster without writing out the full ssh command.
example: kubectl plugin ssh <node-name>
command: ./ssh.sh
flags:
  - name: ssh-user
    shorthand: u
    desc: User to use for the ssh command.
    defValue: admin
  - name: identity-file
    shorthand: i
    desc: Identity file to use for the ssh command.
    defValue: ~/.ssh/id_rsa
